# Generated by Django 5.0.3 on 2024-03-15 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookstore', '0002_rename_name_book_title_remove_book_autor_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='code',
            field=models.IntegerField(default=0, unique=True),
        ),
    ]
