# Generated by Django 5.0.3 on 2024-03-20 01:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookstore', '0005_alter_book_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('image', models.ImageField(null=True, upload_to='booksimg/images/')),
                ('bdate', models.IntegerField(default=0)),
            ],
        ),
    ]
